### ISSUE TITLE
Closing script tag not being colored

### ISSUE THREAD

**Issue by smaili** [atom/language-html#111]
Here's a very simple screenshot where you can see the `</script>` not being properly highlighted in an html file.

![a](https://cloud.githubusercontent.com/assets/4451986/13576584/46cb7014-e443-11e5-9dfb-371269decb92.png)

Looking at the Developer Tools, it appears that the closing `script` is being nested under the `source` element rather than outside of it like the opening `script` tag.

![b](https://cloud.githubusercontent.com/assets/4451986/13576710/e02cc6b8-e443-11e5-914a-670fb4ee9b1a.png)

Is this by design or a bug?

**Comment by kartikanand** [comment]
I'm able to reproduce this issue:

![error](https://cloud.githubusercontent.com/assets/1916792/14432235/db62e44c-0026-11e6-9c8e-b163f89de537.png)

The problem is due to using the keyword `console` directly.

See below, when I replace `console` with `konsole`, it works:

![working](https://cloud.githubusercontent.com/assets/1916792/14432254/f60b568a-0026-11e6-8d16-469aebf3672e.png)

**Comment by 50Wliu** [comment]
I cannot reproduce the original issue on 1.8.0-dev-618bba3.

@kartikanand Your issue is with the language-javascript package - please create a new issue over there.  Thanks!
