### ISSUE TITLE
Syntax highlighting doesn't work

### ISSUE THREAD

**Issue by suvjunmd** [atom/language-html#112]
Atom 1.6.0 on Windows 10.

Syntax highlighting doesn't work for the file https://raw.githubusercontent.com/kangax/compat-table/gh-pages/es6/index.html. Syntax highlighting for other html files from the same repository works as expected.

![1](https://cloud.githubusercontent.com/assets/11020536/13905241/c757788e-eec2-11e5-8273-0f0235a7b306.png)

**Comment by lee-dohm** [comment]
It highlighted for me (after a long, long wait ... but that's probably because the file is over 61KLOC) using Atom v1.8.0-dev-3959259 on Mac OS X 10.11.3. If there is a bug, it is in the general syntax highlighting system, not the language-html package.

Please reopen this on https://github.com/atom/atom and I'll look into it a little more.
