### ISSUE TITLE
css style crash the atom

### ISSUE THREAD

**Issue by LancelotLewis** [atom/language-html#158]
When i write style lable in html file, the application will go crash. But when i disabled the extentsion "language-html", and i write style lable again, everthing is ok.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
