### ISSUE TITLE
editor:move-to-previous-word-boundary isn't consistent with other languages.

### ISSUE THREAD

**Issue by joseramonc** [atom/language-html#184]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

editor:move-to-previous-word-boundary is ignoring hyphens.

### Steps to Reproduce

1. Put cursor after any word-separated-by-hyphen:
![screen shot 2017-12-26 at 2 24 10 pm](https://user-images.githubusercontent.com/1993929/34364141-75510dc4-ea48-11e7-8cd8-1237b1944d0a.png)

2. Resolve editor:move-to-previous-word-boundary

**Expected behavior:** 
![screen shot 2017-12-26 at 2 31 33 pm](https://user-images.githubusercontent.com/1993929/34364239-7ee204aa-ea49-11e7-9054-97eb6c48f652.png)

**Actual behavior:** 
![screen shot 2017-12-26 at 2 32 05 pm](https://user-images.githubusercontent.com/1993929/34364247-93a4f956-ea49-11e7-8811-b75663b560cb.png)

**Reproduces how often:** 100%

### Versions

atom: 1.23.1
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.10
git 2.14.3

OS: high sierra 10.13.2

**Comment by markdrzy** [comment]
This appears to be the commit that changed this behavior: https://github.com/atom/language-html/commit/4fa8731bf51456ae618379aaceb103d2bc2f0b17 I don't understand why dashes would be omitted from the nonWordCharacter list.

**Comment by leroix** [comment]
The editor.nonWordCharacters list was changed because hypen is a valid word character in HTML, and its absence was causing problems (https://github.com/atom/autocomplete-plus/issues/931) in autocomplete-plus. Autocomplete-plus uses the editor.nonWordCharacters setting to determine what constitutes a word boundary.

What constitutes a word is generally language dependent. I'm not super familiar with the history, but it may have been a bug that `-` was originally included as a non-word character in HTML. However, even if it was a bug, other areas of code worked under that assumption, and removing it seems to have made things buggy.

It seems like the best course of action is to add `-` back to non-word characters in this package, language-css, language-less, and language-sass. However, that means that we'll need to come up with a way to fix the bugs it will cause in autocomplete-plus.

**Comment by Rockster160** [comment]
Any way to lock on a previous version to avoid this bug? It's horrendously annoying.

**Comment by jsunsawyer** [comment]
How do I override this? I've tried updating my config.cson and the various language package settings and hyphenated words are still selecting as single words.

**Comment by joseramonc** [comment]
@jsunsawyer this is fixed AFAIK, I think you can test it in [1.25.0 beta](https://github.com/atom/atom/releases) or wait for the release
