### ISSUE TITLE
Support multiline style attribute values

### ISSUE THREAD

**Issue by Ingramz** [atom/language-html#194]
There needs to be a fallback to a multiline `style` attribute if we don't detect a single line one. It does not have to support inline CSS highlighting, but it would be perfect if it did.

See https://github.com/atom/language-php/issues/324#issuecomment-379617659

**Comment by revelt** [comment]
**Atom** `1.27.0beta1` + `language-html` `0.49.0`:
![html_atom](https://user-images.githubusercontent.com/8344688/39753095-828310d4-52b5-11e8-89db-27d48e04c8f3.gif)

**Sublime**, just for a reference:
![html_subl](https://user-images.githubusercontent.com/8344688/39753105-86293e98-52b5-11e8-971b-bfd6bf9ffb3e.gif)

The issue affects not only the pure HTML files, but all derivatives/mixes from HTML language it as well! I came here going to report issue with `HTML-Nunjucks` language, but noticed pure HTML language is affected. Apparently, other language mixes with HTML are affected the same way (like PHP)..

In practice, it's very annoying bug because a single line break within some inline styles breaks formatting for the **rest of the file**...

We should nail all issues like this once and for all because we're _competing_ with Sublime and MSCode...

**Comment by 50Wliu** [comment]
@revelt Thanks for the feedback.  I understand that this is a frustrating issue.  Unfortunately, as a volunteer maintainer, I can only dedicate so much time to working on Atom.  I have a fix up for this now, but in the future, please also consider contributing when you encounter something that you'd like fixed or implemented 🙂.
