### ISSUE TITLE
Add viewport meta tag to `html` snippet

### ISSUE THREAD

**Issue by theel0ja** [atom/language-html#199]

**Comment by theel0ja** [comment]
```cson
'.text.html':
  'HTML':
    'prefix': 'html'
    'body': '<!DOCTYPE html>\n<html lang="${1:en}" dir="${2:ltr}">\n\t<head>\n\t\t<meta charset="utf-8">\n\t\t<meta name="viewport" content="width=device-width, initial-scale=1.0">\n\t\t<title>$3</title>\n\t</head>\n\t<body>\n\t\t$4\n\t</body>\n</html>'
```

**Comment by theel0ja** [comment]
Current one: https://github.com/atom/language-html/blob/b9be363b6d828fcf3d67d3217f5c42415e7500ec/snippets/language-html.cson#L164

**Comment by sdabhi23** [comment]
@50Wliu can I take this up?

**Comment by SupreethBaliga** [comment]
Hi. Is this issue still open? If yes, I would like to take this up.

**Comment by rsese** [comment]
Sorry for the delay here - for now, we're not accepting modifications for snippets in general in the language packages since they are easily overridden and we expect that people will do so for their own purposes. You can find instructions on how to create your own snippets in the [Flight Manual](https://flight-manual.atom.io/using-atom/sections/snippets/). Viewing a language package that provides snippets allows you to copy the current version as a starting place for creating your own.

Thanks again for the suggestion but we're going to leave things as they are for now unless the current snippet produces invalid code.
