### ISSUE TITLE
Language Beautification.

### ISSUE THREAD

**Issue by DaSniper12** [atom/language-html#208]
Hello,

As of late, I started to see that the language formatting is not happening for whatever reason on my laptop, 
I am using Atom 1.28.2, and I also have tried to use a beautifier like Atom-Beautify, but it doesn't help, I want the old formatting back, one reason I think this might be happening is that I use the Atom-FaceBook-IDE.

Regards,
DaCoder

**Comment by Arcanemagus** [comment]
This repository is what provides the syntax highlighting of HTML files within Atom. As this has nothing to do with formatting (re-ordering, beautification, etc.) of the code I'm going to go ahead and close this issue.

It sounds like you might want to file an issue on [`atom-beautify`](https://github.com/Glavin001/atom-beautify), or reach out to [Nuclide](https://nuclide.io/support/) (assuming that's what you mean by "Atom-FaceBook-IDE") in order to try figuring out why this has stopped working.

Thank you for reaching out!
