### ISSUE TITLE
Questions about tree-sitter-html

### ISSUE THREAD

**Issue by caleb531** [atom/language-html#218]
Hi,

Apologies, but I have no bugs to report. I only have two (seemingly related) questions about the tree-sitter grammar for this package:

Firstly, I'm looking at `grammars/tree-sitter-html.cson`, but don't see any definitions for the actual syntactic makeup of an HTML tag—no regular expressions containing `<` and `>` or anything, except in the comment string. If tree-sitter is meant to be a replacement for the regex-based first-mate grammars (as I understand it), where is the basic language syntax defined?

Secondly, the `folds` array references a `start_tag` type, however I cannot find `start_tag` anywhere else in the codebase or in similar Atom repos. Where is `start_tag` actually defined?

Any understanding you could provide would be greatly appreciated!
Caleb

**Comment by caleb531** [comment]
@Aerijo Excellent, thanks—that clears up a bit of confusion for me. If it's not too much trouble, I have one additional question (short answer is fine—I'm just trying to wrap my head around the high-level):

Assuming I've already created a tree sitter grammar and repository, how would I link that to my Atom package? It seems like it would need to be part of the `tree-sitter` org, but I imagine there just be a way to link a custom repository.

I see you're still working on a [tree-sitter guide for Atom](https://gist.github.com/Aerijo/df27228d70c633e088b0591b8857eeef), so don't feel the need to be too specific with your answer here.

**Comment by Aerijo** [comment]
@caleb531 The parser itself belongs in it's own repository, under any name. For it to be used in a published Atom package, it must be published to NPM (it's possible to link it locally if you don't want to publish to NPM yet).

This parser takes most of the work; it has the grammar definition, and you add the tests here (typically in the `corpus` folder) to make sure it's doing what it should. Note this parser actually creates a syntax tree for what it parses, where things like `start_tag` are nodes.

On the Atom side, you register it as a dependency like normal, and make a file [like this one](https://github.com/Aerijo/language-latex2e/blob/master/grammars/tree-sitter-biber.cson). The `scopes` key translates nodes to CSS scopes, which are what themes can target. There's a lot more you can do here, like use regex to further refine the CSS scopes, but I'm not sure on the syntax right now.

There can be versioning issues, but I think the guide is still up to date on that. Also, once you get a working grammar, you should look at pre-building the parser using CI. This means the end user won't need build tools installed (which they do if it's not pre built).

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
