### ISSUE TITLE
update the favicon snippet

### ISSUE THREAD

**Issue by unluisco** [atom/language-html#219]
### Prerequisites

- No needed. It's only a suggestion.

### Description

Should we update the favicon snippet?
 this line contain the snippet: https://github.com/atom/language-html/blob/master/snippets/language-html.cson#L116

but according to this article: https://mathiasbynens.be/notes/rel-shortcut-icon
and this stackoverflow answer: https://stackoverflow.com/a/31132296

there ir no needed to write 'shortcut' in the type property.

and because we can use png and other types of images, can we delete the default '.ico' extension?

If so, can I do the change?

Thanks for your time.

**Comment by rsese** [comment]
Thanks for the suggestion and for checking in with us!  See Lee's comment here /cc https://github.com/atom/language-html/pull/210#issuecomment-424493889 - at the moment we're generally not accepting language package snippets changes since snippets can be customized easily and we expect that people will customize them for their own needs.

Since we wouldn't accept a pull request to update this snippet, I'll go ahead and close the issue but thanks again for your interest!
