### ISSUE TITLE
Tag and string punctuation is not targetable in the tree-sitter grammar

### ISSUE THREAD

**Issue by Aerijo** [atom/language-html#224]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With the Tree-sitter grammar, there is no scope on the `<`, `</`, `>` and `"` characters. This means the user / theme cannot target them for custom colours.

### Steps to Reproduce

1. Inspect the scope of one of these characters; it is just `text.html.basic source.html`
2. Disable Tree-sitter and refresh the grammar
3. Inspect the scopes; each can now be targeted independently.

**Expected behavior:** [What you expect to happen]

Tree-sitter allows equal customisation

**Actual behavior:** [What actually happens]

No target

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

language-html 0.51.5

### Additional Information

See [the discuss post](https://discuss.atom.io/t/is-it-possible-to-colorize-the-brackets-of-html-tags-like-in-dreamweaver-and-brackets/62084) for at least one motivation.

**Comment by rsese** [comment]
Thanks @Aerijo!  I might be misunderstanding so let me know :smile:  

I tried 1.34.0 with Tree-sitter enabled and your styles from https://discuss.atom.io/t/is-it-possible-to-colorize-the-brackets-of-html-tags-like-in-dreamweaver-and-brackets/62084 and see this:

![html-punctuation](https://github-slack.s3.amazonaws.com/monosnap/styles.less__.atom_2019-01-24_19-52-53.png)

Based on your description, I was expecting the brackets to not be affected by the CSS?

**Comment by Aerijo** [comment]
@rsese You appear to be using the TextMate grammar there (see the `console.log` statement using the TextMate grammar colours). This will happen if you switch the grammar manually, otr there may be something in your config that disabled Tree-sitter for HTML?

**Comment by rsese** [comment]
Ohhh yeah you're right :+1:  I have to manually select `HTML` with the grammar selector for that particular example file I was using to have it use the Tree-sitter grammar (I didn't see anything in my config for HTML...).  If I close and reopen it, I have to manually select `HTML` again (doesn't seem to happen if I remove the `<script>` tag though).

In any case, thanks for explaining :+1:

**Comment by PlaidPhantom** [comment]
Let me know if this needs to be a new ticket, but entities (e.g. `&nbsp;`) are not targetable either.

**Comment by savetheclocktower** [comment]
@PlaidPhantom, I'd say that would require a new ticket because the fix isn't as straightforward.

The underlying problem there is that `tree-sitter-html` doesn't mark entities as entities. Consider:

```html
<p>Lorem ipsum dolor &nbsp; sit amet</p>
```

The `tree-sitter-html` parser will mark the entire `Lorem ipsum dolor &nbsp; sit amet` section as `text`, but would apply no further markings. It appears that the parser [has not considered entities at all](https://github.com/tree-sitter/tree-sitter-html/search?q=entity&unscoped_q=entity).

I'd suggest you [open a ticket against `tree-sitter-html`](https://github.com/tree-sitter/tree-sitter-html/issues) to find out if the omission is intentional or if it's just not yet implemented. My guess is the latter. (If it's an intentional omission, then I think `language-html` could implement the highlighting of entities as an injection grammar with some effort.)
