### ISSUE TITLE
Including text.html.basic stops further highlighting in parent grammar

### ISSUE THREAD

**Issue by MaxGiting** [atom/language-html#62]
In my Smarty Grammar I include this language to highlight the HTML. But after the first HTML tag all further smarty syntax highlighting stops.

If I change this or remove this line the smarty highlighting carries through the entire file
https://github.com/MaxGiting/atom-language-smarty/blob/master/grammars/smarty.cson#L16

I have also tested with this package and seen the same issue.
https://atom.io/packages/language-smarty-php

**Comment by taylon** [comment]
I'm having the same issue in the atom-handlebars package (https://github.com/Sneagan/atom-handlebars/pull/27), tested on language-mustache and same problem there, also https://github.com/atom/language-ruby/issues/95 

Probably all packages that include language-html are broken right now =/

**Comment by taylon** [comment]
Hey @benogle 

I debugged this and found out that what is causing this issue are the following lines:

```
    {
      'begin': '(?<=>)'
      'end': '(?=<)'
      'name': 'meta.scope.outside-tag.html'
      'patterns': [
        {
          'include': '#entities'
        }
      ]
    }
```

Those were added in this commit: https://github.com/atom/language-html/commit/bc7c4c9ffcb19d9de77fef670179c8ac4ae5cd52

I didn't create a pull request because I'm not sure what that code is supposed to do. It's matching everything outside html tags which overrides what we set in grammars that include language-html, that is why the first line of the file works and the others don't:

![screen shot 2015-05-22 at 21 36 08](https://cloud.githubusercontent.com/assets/79991/7782421/cc9cd23a-00ca-11e5-9a43-ba674c00ad7e.png)

And without that code:

![screen shot 2015-05-22 at 21 36 58](https://cloud.githubusercontent.com/assets/79991/7782423/d731ade2-00ca-11e5-8530-88170dca4da1.png)

If you give me any direction or clarity around why those lines were added I can try to fix it =D

**Comment by benogle** [comment]
Closing in favor of #60. I will fix this before the next release. Thanks @taylon for the offer.
