### ISSUE TITLE
Template in Meteor

### ISSUE THREAD

**Issue by onero** [atom/language-html#84]
It would be awesome if the autcomplete for "template" could be 

``` html
<template name="">

</template>
```

instead of 

``` html
<template id="">
  
</template>
```

Since the latter will not qualify as valid in meteor.

**Comment by mnquintana** [comment]
You can create your own snippet for this by editing [your `snippets.cson` file](https://atom.io/docs/latest/using-atom-snippets#creating-your-own-snippets):

```cson
'.text.html':
  'Template with name':
    'prefix': 'template'
    'body': """
      <template name="$0">
        $1
      </template>
    """
```

I'm not sure that using `name` is generalizable enough to replace use of `id` here, since this isn't a Meteor-specific package.

Does that help?

**Comment by onero** [comment]
Thanks for your reply!
It helps out quite a lot.

Adam.
